"""
Quotation & Metering System.

Handles the economics of M2M interactions:

1. Quote Generation — estimate cost based on task complexity
2. Credit Management — prepaid credit balance per agent
3. Usage Metering — track what was consumed
4. Settlement — create audit-ready billing records

Pricing model:
    Each service has a base_price_credits. The actual cost
    is adjusted by complexity multipliers:
    - Field count: more fields = higher cost
    - Attachment count: images/PDFs = higher cost
    - Verification depth: GOLD requires more compute
    - Region: some regions have harder anti-bot friction
"""
import asyncio
import logging
import secrets
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger("Quotation")


@dataclass
class Quote:
    """
    A price quote for a requested task.

    Generated by The Last Bastion in response to a QUOTE_REQUEST.
    Valid for a limited time (quote_ttl_seconds).
    """
    quote_id: str
    service_id: str
    agent_id: str                    # Who requested the quote
    estimated_credits: float         # Total estimated cost
    breakdown: Dict[str, float] = field(default_factory=dict)
    quote_ttl_seconds: int = 300     # Valid for 5 minutes
    created_at: str = ""
    is_accepted: bool = False
    is_expired: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.created_at:
            self.created_at = datetime.utcnow().isoformat()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "quote_id": self.quote_id,
            "service_id": self.service_id,
            "agent_id": self.agent_id,
            "estimated_credits": round(self.estimated_credits, 4),
            "breakdown": {
                k: round(v, 4) for k, v in self.breakdown.items()
            },
            "quote_ttl_seconds": self.quote_ttl_seconds,
            "created_at": self.created_at,
            "is_accepted": self.is_accepted,
        }


@dataclass
class UsageRecord:
    """A single metered usage event."""
    record_id: str
    agent_id: str
    service_id: str
    credits_consumed: float
    task_id: Optional[str] = None
    fields_processed: int = 0
    attachments_processed: int = 0
    verification_verdict: str = ""
    timestamp: str = ""

    def __post_init__(self) -> None:
        if not self.timestamp:
            self.timestamp = datetime.utcnow().isoformat()


class QuotationEngine:
    """
    Generates quotes and manages credits for M2M billing.

    Credit system:
    - Agents pre-purchase credits
    - Each task deducts from their balance
    - Usage is metered and recorded
    - Settlement records are audit-ready
    """

    # Complexity multipliers
    FIELD_MULTIPLIER = 0.1          # Per field beyond 5
    ATTACHMENT_MULTIPLIER = 1.0      # Per attachment
    VERIFICATION_MULTIPLIER = 0.5   # For verification services
    REGION_DIFFICULTY = {
        "nz": 1.0,     # Baseline
        "au": 1.0,
        "us": 1.2,     # Higher anti-bot friction
        "uk": 1.1,
        "global": 1.3,
    }

    # How often generate_quote() opportunistically purges expired quotes —
    # not on every call (that'd be an O(n) scan per request), just periodically
    _QUOTE_CLEANUP_INTERVAL_SECONDS = 60
    # Cap on in-memory usage history — this is a live metering cache, not the
    # audit trail (that's persisted to DB); an unbounded list here grows
    # forever for the life of the process
    _MAX_USAGE_HISTORY = 10_000

    def __init__(self) -> None:
        # agent_id -> credit balance
        self._balances: Dict[str, float] = {}
        # quote_id -> Quote
        self._quotes: Dict[str, Quote] = {}
        # Usage history — bounded, oldest evicted first
        self._usage: deque = deque(maxlen=self._MAX_USAGE_HISTORY)
        self._stats = {
            "quotes_generated": 0,
            "quotes_accepted": 0,
            "total_credits_consumed": 0.0,
        }
        self._last_quote_cleanup = datetime.utcnow()

    def _purge_expired_quotes(self) -> None:
        """
        Evicts quotes past their TTL from the live dict. Without this, every
        quote ever generated (accepted or not) stays in memory for the entire
        life of the process — a guaranteed unbounded leak on any server that
        handles /m2m/quote traffic continuously.
        """
        now = datetime.utcnow()
        expired_ids = []
        for qid, q in self._quotes.items():
            try:
                created = datetime.fromisoformat(q.created_at)
                if (now - created).total_seconds() > q.quote_ttl_seconds:
                    expired_ids.append(qid)
            except ValueError:
                expired_ids.append(qid)  # Unparsable timestamp — drop it too
        for qid in expired_ids:
            del self._quotes[qid]
        if expired_ids:
            logger.debug(f"Purged {len(expired_ids)} expired quotes")

    async def add_credits(self, agent_id: str, amount: float) -> float:
        """
        Adds credits to an agent's balance. Persisted to DB so it survives
        restarts and is shared across worker processes; the in-memory dict is
        kept as a fallback for when the DB is unavailable.

        Runs the (synchronous, psycopg2-backed) DB call in a worker thread via
        asyncio.to_thread — every core.database call is blocking, and calling
        one directly from an `async def` FastAPI handler stalls the entire
        event loop for the DB round-trip, freezing every OTHER concurrent
        request (unrelated agents included) for that duration.

        Returns: New balance
        """
        try:
            from core.database import add_credit_balance
            new_balance = await asyncio.to_thread(add_credit_balance, agent_id, amount)
            self._balances[agent_id] = new_balance
        except Exception as e:
            logger.warning(f"CREDITS: DB persist failed ({e}), using in-memory only")
            self._balances[agent_id] = self._balances.get(agent_id, 0.0) + amount

        logger.info(
            f"CREDITS: +{amount:.2f} for {agent_id}, "
            f"balance={self._balances[agent_id]:.2f}"
        )
        return self._balances[agent_id]

    async def get_balance(self, agent_id: str) -> float:
        """Returns an agent's current credit balance (DB-backed, falls back to in-memory cache)."""
        try:
            from core.database import get_credit_balance
            return await asyncio.to_thread(get_credit_balance, agent_id)
        except Exception as e:
            logger.warning(f"BALANCE: DB read failed ({e}), using in-memory cache")
            return self._balances.get(agent_id, 0.0)

    def generate_quote(
        self,
        agent_id: str,
        service_id: str,
        task_params: Dict[str, Any],
    ) -> Quote:
        """
        Generates a price quote for a task.

        Pricing formula:
            base_price
            + (field_count - 5) × FIELD_MULTIPLIER     (if > 5 fields)
            + attachment_count × ATTACHMENT_MULTIPLIER
            × region_difficulty
        """
        now = datetime.utcnow()
        if (now - self._last_quote_cleanup).total_seconds() > self._QUOTE_CLEANUP_INTERVAL_SECONDS:
            self._purge_expired_quotes()
            self._last_quote_cleanup = now

        # Base prices by service
        base_prices = {
            "svc-data-extraction": 5.0,
            "svc-document-verification": 3.0,
            "svc-market-intelligence": 2.0,
            "svc-attestation-proof": 4.0,
        }
        base = base_prices.get(service_id, 5.0)

        # Complexity adjustments
        field_count = task_params.get("field_count", 5)
        attachment_count = task_params.get("attachment_count", 0)
        region = task_params.get("region", "nz")

        field_cost = max(0, (field_count - 5)) * self.FIELD_MULTIPLIER
        attachment_cost = attachment_count * self.ATTACHMENT_MULTIPLIER
        region_mult = self.REGION_DIFFICULTY.get(region, 1.0)

        total = (base + field_cost + attachment_cost) * region_mult

        quote = Quote(
            quote_id=f"qt-{secrets.token_hex(6)}",
            service_id=service_id,
            agent_id=agent_id,
            estimated_credits=round(total, 4),
            breakdown={
                "base": base,
                "field_complexity": round(field_cost, 4),
                "attachments": round(attachment_cost, 4),
                "region_multiplier": region_mult,
                "total": round(total, 4),
            },
        )

        self._quotes[quote.quote_id] = quote
        self._stats["quotes_generated"] += 1

        logger.info(
            f"QUOTE: {quote.quote_id} for {agent_id} — "
            f"{service_id} = {total:.4f} credits"
        )
        return quote

    async def accept_quote(self, quote_id: str) -> bool:
        """
        Accepts a quote and deducts credits from the agent's balance.

        Returns False if insufficient balance or quote expired.
        """
        quote = self._quotes.get(quote_id)
        if not quote:
            logger.warning(f"Quote not found: {quote_id}")
            return False

        if quote.is_accepted:
            logger.warning(f"Quote already accepted: {quote_id}")
            return False

        # Check expiry
        try:
            created = datetime.fromisoformat(quote.created_at)
            age = (datetime.utcnow() - created).total_seconds()
            if age > quote.quote_ttl_seconds:
                quote.is_expired = True
                logger.warning(f"Quote expired: {quote_id}")
                return False
        except ValueError:
            pass

        # Check + deduct credits atomically. deduct_credit_balance() does the
        # balance check and the deduction as a single conditional DB UPDATE
        # (WHERE balance >= amount), so two concurrent accept_quote() calls —
        # even across different worker processes — can't both pass a
        # check-then-deduct race and double-spend the same balance. Run via
        # asyncio.to_thread so this blocking DB round-trip doesn't stall the
        # event loop for every other concurrent request.
        try:
            from core.database import deduct_credit_balance
            deducted = await asyncio.to_thread(
                deduct_credit_balance, quote.agent_id, quote.estimated_credits
            )
        except Exception as e:
            logger.warning(f"ACCEPT: DB deduct failed ({e}), falling back to in-memory check")
            balance = self._balances.get(quote.agent_id, 0.0)
            deducted = balance >= quote.estimated_credits
            if deducted:
                self._balances[quote.agent_id] = balance - quote.estimated_credits

        if not deducted:
            logger.warning(
                f"Insufficient credits: {quote.agent_id} needs {quote.estimated_credits:.2f}"
            )
            return False

        self._balances[quote.agent_id] = await self.get_balance(quote.agent_id)
        quote.is_accepted = True
        self._stats["quotes_accepted"] += 1
        self._stats["total_credits_consumed"] += quote.estimated_credits

        logger.info(
            f"ACCEPTED: {quote_id} — deducted {quote.estimated_credits:.2f} "
            f"from {quote.agent_id}, remaining={self._balances[quote.agent_id]:.2f}"
        )
        return True

    def record_usage(
        self,
        agent_id: str,
        service_id: str,
        credits_consumed: float,
        task_id: Optional[str] = None,
        fields_processed: int = 0,
        attachments_processed: int = 0,
        verification_verdict: str = "",
    ) -> UsageRecord:
        """Records a metered usage event."""
        record = UsageRecord(
            record_id=f"use-{secrets.token_hex(6)}",
            agent_id=agent_id,
            service_id=service_id,
            credits_consumed=credits_consumed,
            task_id=task_id,
            fields_processed=fields_processed,
            attachments_processed=attachments_processed,
            verification_verdict=verification_verdict,
        )
        self._usage.append(record)
        return record

    def get_usage_summary(self, agent_id: str) -> Dict[str, Any]:
        """Returns usage summary for an agent."""
        agent_usage = [
            u for u in self._usage if u.agent_id == agent_id
        ]
        total_credits = sum(u.credits_consumed for u in agent_usage)
        total_requests = len(agent_usage)

        return {
            "agent_id": agent_id,
            "total_requests": total_requests,
            "total_credits_consumed": round(total_credits, 4),
            "current_balance": round(self.get_balance(agent_id), 4),
        }

    @property
    def stats(self) -> Dict[str, Any]:
        return {
            **self._stats,
            "total_credits_consumed": round(
                self._stats["total_credits_consumed"], 4
            ),
        }
