"""
Blockchain Anchor — Submits Proof Records & Agent Data On-Chain.

Connects the off-chain systems to TWO on-chain contracts via web3.py:
  1. SwarmProofRegistry — data verification proofs
  2. SwarmAgentRegistry — M2M agent identity, reputation, services, task receipts

This is NOT a simulation. It makes REAL transactions on a REAL
blockchain (Polygon Amoy testnet or mainnet, configurable).

Flow:
    ProofLedger records verdict
    -> BlockchainAnchor.anchor(record)
    -> web3.py signs + sends transaction
    -> SwarmProofRegistry.anchorProof() stores on-chain
    -> Transaction hash returned as receipt

Requirements:
    pip install web3
    Environment variables:
        BLOCKCHAIN_RPC_URL      — RPC endpoint (e.g., Polygon Amoy)
        BLOCKCHAIN_PRIVATE_KEY   — Deployer/submitter private key
        PROOF_REGISTRY_ADDRESS   — Deployed SwarmProofRegistry address
        AGENT_REGISTRY_ADDRESS   — Deployed SwarmAgentRegistry address (optional)
"""
import hashlib
import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("BlockchainAnchor")

# Contract ABI paths (generated by Hardhat/Foundry after compilation)
CONTRACT_ABI_PATH = Path(__file__).parent.parent / "contracts" / "SwarmProofRegistry.abi.json"
AGENT_REGISTRY_ABI_PATH = Path(__file__).parent.parent / "contracts" / "SwarmAgentRegistry.abi.json"


class BlockchainAnchor:
    """
    Real blockchain integration for proof anchoring and M2M agent registry.

    Connects to TWO contracts on a configured EVM chain:
      1. SwarmProofRegistry  — data verification proofs
      2. SwarmAgentRegistry  — agent identity, reputation, services, task receipts

    Supports:
    - Single proof anchoring + batch anchoring (SwarmProofRegistry)
    - On-chain proof verification (read-only, no gas)
    - Agent registration, reputation updates (SwarmAgentRegistry)
    - Service registration, task receipt recording (SwarmAgentRegistry)
    - Agent lookup (read-only, no gas)
    """

    def __init__(
        self,
        rpc_url: Optional[str] = None,
        private_key: Optional[str] = None,
        contract_address: Optional[str] = None,
    ) -> None:
        self._rpc_url = rpc_url or os.getenv(
            "BLOCKCHAIN_RPC_URL", ""
        )
        self._private_key = private_key or os.getenv(
            "BLOCKCHAIN_PRIVATE_KEY", ""
        )
        self._contract_address = contract_address or os.getenv(
            "PROOF_REGISTRY_ADDRESS", ""
        )
        self._agent_registry_address = os.getenv(
            "AGENT_REGISTRY_ADDRESS", ""
        )

        self._web3 = None
        self._contract = None
        self._agent_contract = None
        self._account = None
        self._is_connected = False
        self._agent_registry_connected = False
        # Receipts stored in BlockchainStamp table — no in-memory accumulation needed

        self._stats = {
            "proofs_anchored": 0,
            "batches_submitted": 0,
            "agents_registered": 0,
            "reputation_updates": 0,
            "task_receipts_recorded": 0,
            "total_gas_used": 0,
            "failed_transactions": 0,
        }

        # Attempt connection if config is present
        if self._rpc_url and self._private_key and self._contract_address:
            self._connect()
        else:
            logger.warning(
                "BLOCKCHAIN: Not configured — set BLOCKCHAIN_RPC_URL, "
                "BLOCKCHAIN_PRIVATE_KEY, and PROOF_REGISTRY_ADDRESS "
                "environment variables to enable on-chain anchoring."
            )

    def _connect(self) -> None:
        """Connects to the blockchain and loads the contract."""
        try:
            from web3 import Web3
            from web3.middleware import ExtraDataToPOAMiddleware

            self._web3 = Web3(Web3.HTTPProvider(self._rpc_url))

            # Polygon and other PoA chains need this middleware
            self._web3.middleware_onion.inject(
                ExtraDataToPOAMiddleware, layer=0
            )

            if not self._web3.is_connected():
                logger.error(
                    f"BLOCKCHAIN: Cannot connect to {self._rpc_url}"
                )
                return

            chain_id = self._web3.eth.chain_id
            self._account = self._web3.eth.account.from_key(
                self._private_key
            )

            # Load contract ABI
            abi = self._load_abi()
            if not abi:
                return

            self._contract = self._web3.eth.contract(
                address=Web3.to_checksum_address(self._contract_address),
                abi=abi,
            )

            self._is_connected = True
            balance = self._web3.eth.get_balance(self._account.address)
            balance_eth = self._web3.from_wei(balance, "ether")

            logger.info(
                f"BLOCKCHAIN: Connected to chain {chain_id} "
                f"({self._rpc_url[:40]}...), "
                f"account={self._account.address[:10]}..., "
                f"balance={balance_eth:.6f} native"
            )

            # Connect to SwarmAgentRegistry (optional — degrades gracefully)
            if self._agent_registry_address:
                try:
                    agent_abi = self._load_agent_registry_abi()
                    if agent_abi:
                        self._agent_contract = self._web3.eth.contract(
                            address=Web3.to_checksum_address(
                                self._agent_registry_address
                            ),
                            abi=agent_abi,
                        )
                        self._agent_registry_connected = True
                        logger.info(
                            f"BLOCKCHAIN: AgentRegistry connected at "
                            f"{self._agent_registry_address[:10]}..."
                        )
                except Exception as agent_exc:
                    logger.warning(
                        f"BLOCKCHAIN: AgentRegistry connection failed — {agent_exc}. "
                        "Agent registry features disabled."
                    )
            else:
                logger.info(
                    "BLOCKCHAIN: AGENT_REGISTRY_ADDRESS not set — "
                    "agent registry features disabled."
                )

        except ImportError:
            logger.error(
                "BLOCKCHAIN: web3 not installed. "
                "Run: pip install web3"
            )
        except Exception as exc:
            logger.error(f"BLOCKCHAIN: Connection failed — {exc}")

    def _load_abi(self) -> Optional[List[Dict]]:
        """Loads the SwarmProofRegistry ABI from file."""
        if CONTRACT_ABI_PATH.exists():
            with open(CONTRACT_ABI_PATH, "r") as f:
                return json.load(f)

        # Fallback: minimal ABI for the functions we use
        logger.warning(
            f"BLOCKCHAIN: ABI file not found at {CONTRACT_ABI_PATH}, "
            "using inline ABI"
        )
        return self._inline_abi()

    def _load_agent_registry_abi(self) -> Optional[List[Dict]]:
        """Loads the SwarmAgentRegistry ABI from file."""
        if AGENT_REGISTRY_ABI_PATH.exists():
            with open(AGENT_REGISTRY_ABI_PATH, "r") as f:
                return json.load(f)

        # Fallback: inline ABI for the agent registry functions
        logger.warning(
            f"BLOCKCHAIN: Agent registry ABI not found at "
            f"{AGENT_REGISTRY_ABI_PATH}, using inline ABI"
        )
        return self._agent_registry_inline_abi()

    @property
    def is_connected(self) -> bool:
        """Whether the blockchain connection is live."""
        return self._is_connected

    @property
    def stats(self) -> Dict[str, Any]:
        """Returns anchoring statistics."""
        return dict(self._stats)

    def anchor_proof(
        self, proof_record: Dict[str, Any]
    ) -> Optional[Dict[str, Any]]:
        """
        Anchors a single proof record on-chain.

        Args:
            proof_record: Output from ProofRecord.to_smart_contract_args()

        Returns:
            Transaction receipt dict, or None if failed.
        """
        if not self._is_connected:
            logger.warning(
                "BLOCKCHAIN: Not connected — proof not anchored. "
                "Configure environment variables to enable."
            )
            return None

        try:
            tx = self._contract.functions.anchorProof(
                bytes.fromhex(proof_record["payloadHash"][2:]),
                bytes.fromhex(proof_record["evidenceHash"][2:]),
                bytes.fromhex(proof_record["provenanceHash"][2:]),
                bytes.fromhex(proof_record["previousHash"][2:]),
                bytes.fromhex(proof_record["blockHash"][2:]),
                proof_record["verdict"],
                proof_record["score"],
                proof_record["timestamp"],
            )

            receipt = self._send_transaction(tx)
            if receipt:
                self._stats["proofs_anchored"] += 1
                logger.info(
                    f"ANCHORED: {proof_record['blockHash'][:18]}... "
                    f"-> tx={receipt['transactionHash'][:18]}..."
                )
            return receipt

        except Exception as exc:
            self._stats["failed_transactions"] += 1
            logger.error(f"ANCHOR FAILED: {exc}")
            return None

    def anchor_batch(
        self, proof_records: List[Dict[str, Any]]
    ) -> Optional[Dict[str, Any]]:
        """
        Anchors a batch of proof records in a single transaction.

        More gas-efficient than individual anchoring.
        """
        if not self._is_connected:
            logger.warning("BLOCKCHAIN: Not connected — batch not anchored.")
            return None

        if not proof_records:
            return None

        try:
            # Prepare parallel arrays for the batch function
            payload_hashes = []
            evidence_hashes = []
            provenance_hashes = []
            previous_hashes = []
            block_hashes = []
            verdicts = []
            scores = []
            timestamps = []

            for record in proof_records:
                payload_hashes.append(
                    bytes.fromhex(record["payloadHash"][2:])
                )
                evidence_hashes.append(
                    bytes.fromhex(record["evidenceHash"][2:])
                )
                provenance_hashes.append(
                    bytes.fromhex(record["provenanceHash"][2:])
                )
                previous_hashes.append(
                    bytes.fromhex(record["previousHash"][2:])
                )
                block_hashes.append(
                    bytes.fromhex(record["blockHash"][2:])
                )
                verdicts.append(record["verdict"])
                scores.append(record["score"])
                timestamps.append(record["timestamp"])

            tx = self._contract.functions.anchorBatch(
                payload_hashes,
                evidence_hashes,
                provenance_hashes,
                previous_hashes,
                block_hashes,
                verdicts,
                scores,
                timestamps,
            )

            receipt = self._send_transaction(tx)
            if receipt:
                self._stats["proofs_anchored"] += len(proof_records)
                self._stats["batches_submitted"] += 1
                logger.info(
                    f"BATCH ANCHORED: {len(proof_records)} records "
                    f"-> tx={receipt['transactionHash'][:18]}..."
                )
            return receipt

        except Exception as exc:
            self._stats["failed_transactions"] += 1
            logger.error(f"BATCH ANCHOR FAILED: {exc}")
            return None

    def verify_on_chain(
        self, block_hash: str
    ) -> Optional[Dict[str, Any]]:
        """
        Queries the smart contract to verify a proof hash.

        This is a READ-ONLY call — no gas cost.
        Anyone can call this to check if data was verified.
        """
        if not self._is_connected:
            return None

        try:
            # Ensure the hash is valid hex and bytes32
            hex_str = block_hash[2:] if block_hash.startswith("0x") else block_hash
            try:
                hash_bytes = bytes.fromhex(hex_str)
            except ValueError:
                logger.debug(f"BLOCKCHAIN: Invalid proof hash format: {block_hash}")
                return None

            exists, verdict, score, timestamp, payload_hash = (
                self._contract.functions.verifyProof(hash_bytes).call()
            )

            if not exists:
                return {
                    "exists": False,
                    "block_hash": block_hash,
                    "source": "blockchain",
                }

            verdict_names = {
                0: "REJECTED",
                1: "QUARANTINE",
                2: "VERIFIED",
                3: "GOLD",
            }

            return {
                "exists": True,
                "block_hash": block_hash,
                "verdict": verdict_names.get(verdict, "UNKNOWN"),
                "score": score / 1_000_000,
                "timestamp": timestamp,
                "payload_hash": f"0x{payload_hash.hex()}",
                "source": "blockchain",
            }

        except Exception as exc:
            logger.error(f"ON-CHAIN VERIFY FAILED: {exc}")
            return None

    def get_chain_stats(self) -> Optional[Dict[str, Any]]:
        """
        Gets on-chain statistics from the contract.

        READ-ONLY — no gas cost.
        """
        if not self._is_connected:
            return None

        try:
            chain_len = self._contract.functions.chainLength().call()
            rejected, quarantined, verified, gold = (
                self._contract.functions.getVerdictCounts().call()
            )

            return {
                "chain_length": chain_len,
                "total_proofs": chain_len,
                "verdict_counts": {
                    "REJECTED": rejected,
                    "QUARANTINE": quarantined,
                    "VERIFIED": verified,
                    "GOLD": gold,
                },
                "source": "blockchain",
            }

        except Exception as exc:
            logger.error(f"ON-CHAIN STATS FAILED: {exc}")
            return None

    def _send_transaction(self, tx_function) -> Optional[Dict[str, Any]]:
        """
        Signs and sends a transaction, waits for receipt.

        Returns the transaction receipt or None.
        """
        try:
            # Build transaction
            nonce = self._web3.eth.get_transaction_count(
                self._account.address
            )
            gas_price = self._web3.eth.gas_price

            tx_data = tx_function.build_transaction({
                "from": self._account.address,
                "nonce": nonce,
                "gasPrice": gas_price,
                "chainId": self._web3.eth.chain_id,
            })

            # Estimate gas
            gas_estimate = self._web3.eth.estimate_gas(tx_data)
            tx_data["gas"] = int(gas_estimate * 1.2)  # 20% buffer

            # Sign
            signed = self._web3.eth.account.sign_transaction(
                tx_data, private_key=self._private_key
            )

            # Send
            tx_hash = self._web3.eth.send_raw_transaction(
                signed.raw_transaction
            )

            # Wait for receipt (timeout 120s)
            receipt = self._web3.eth.wait_for_transaction_receipt(
                tx_hash, timeout=120
            )

            gas_used = receipt.get("gasUsed", 0)
            self._stats["total_gas_used"] += gas_used

            receipt_dict = {
                "transactionHash": receipt["transactionHash"].hex(),
                "blockNumber": receipt["blockNumber"],
                "gasUsed": gas_used,
                "status": receipt["status"],  # 1 = success, 0 = revert
            }
            if receipt["status"] != 1:
                logger.error(
                    f"TX REVERTED: {receipt_dict['transactionHash'][:18]}..."
                )
                self._stats["failed_transactions"] += 1
                return None

            return receipt_dict

        except Exception as exc:
            logger.error(f"TX FAILED: {exc}")
            self._stats["failed_transactions"] += 1
            return None

    @staticmethod
    def _inline_abi() -> List[Dict]:
        """
        Inline ABI for SwarmProofRegistry.

        This matches the Solidity contract exactly.
        Used as fallback when the compiled ABI file is not present.
        """
        return [
            {
                "inputs": [],
                "stateMutability": "nonpayable",
                "type": "constructor",
            },
            {
                "inputs": [
                    {"name": "payloadHash", "type": "bytes32"},
                    {"name": "evidenceHash", "type": "bytes32"},
                    {"name": "provenanceHash", "type": "bytes32"},
                    {"name": "previousHash", "type": "bytes32"},
                    {"name": "blockHash", "type": "bytes32"},
                    {"name": "verdict", "type": "uint8"},
                    {"name": "score", "type": "uint256"},
                    {"name": "timestamp", "type": "uint256"},
                ],
                "name": "anchorProof",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            },
            {
                "inputs": [
                    {"name": "payloadHashes", "type": "bytes32[]"},
                    {"name": "evidenceHashes", "type": "bytes32[]"},
                    {"name": "provenanceHashes", "type": "bytes32[]"},
                    {"name": "previousHashes", "type": "bytes32[]"},
                    {"name": "blockHashes", "type": "bytes32[]"},
                    {"name": "verdicts", "type": "uint8[]"},
                    {"name": "scores", "type": "uint256[]"},
                    {"name": "timestamps", "type": "uint256[]"},
                ],
                "name": "anchorBatch",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            },
            {
                "inputs": [
                    {"name": "blockHash", "type": "bytes32"},
                ],
                "name": "verifyProof",
                "outputs": [
                    {"name": "exists", "type": "bool"},
                    {"name": "verdict", "type": "uint8"},
                    {"name": "score", "type": "uint256"},
                    {"name": "timestamp", "type": "uint256"},
                    {"name": "payloadHash", "type": "bytes32"},
                ],
                "stateMutability": "view",
                "type": "function",
            },
            {
                "inputs": [],
                "name": "chainLength",
                "outputs": [
                    {"name": "", "type": "uint256"},
                ],
                "stateMutability": "view",
                "type": "function",
            },
            {
                "inputs": [],
                "name": "getVerdictCounts",
                "outputs": [
                    {"name": "rejected", "type": "uint256"},
                    {"name": "quarantined", "type": "uint256"},
                    {"name": "verified", "type": "uint256"},
                    {"name": "gold", "type": "uint256"},
                ],
                "stateMutability": "view",
                "type": "function",
            },
            {
                "inputs": [
                    {"name": "blockHash", "type": "bytes32"},
                ],
                "name": "getProof",
                "outputs": [
                    {
                        "components": [
                            {"name": "payloadHash", "type": "bytes32"},
                            {"name": "evidenceHash", "type": "bytes32"},
                            {"name": "provenanceHash", "type": "bytes32"},
                            {"name": "previousHash", "type": "bytes32"},
                            {"name": "blockHash", "type": "bytes32"},
                            {"name": "verdict", "type": "uint8"},
                            {"name": "score", "type": "uint256"},
                            {"name": "timestamp", "type": "uint256"},
                            {"name": "submitter", "type": "address"},
                        ],
                        "name": "",
                        "type": "tuple",
                    }
                ],
                "stateMutability": "view",
                "type": "function",
            },
        ]

    # =========================================================================
    # SwarmAgentRegistry — M2M Agent Marketplace Methods
    # =========================================================================

    @staticmethod
    def _to_bytes32(value: str) -> bytes:
        """
        Converts a string to keccak256 bytes32 for on-chain storage.

        The Solidity contract stores all IDs as keccak256 hashes (bytes32)
        for gas efficiency. This helper matches that convention.

        IMPORTANT: Ethereum uses Keccak-256 (pre-NIST), NOT SHA3-256 (NIST).
        They differ in padding. We use Web3's keccak to match Solidity.
        """
        try:
            from web3 import Web3
            return Web3.keccak(text=value)
        except ImportError:
            # Fallback: warn and use sha3_256 (close but not identical to keccak)
            logger.warning(
                "web3 not available for keccak256 — using sha3_256 fallback. "
                "On-chain lookups may not match Solidity keccak256()."
            )
            return hashlib.sha3_256(value.encode()).digest()

    def register_agent_on_chain(
        self,
        agent_id: str,
        public_key: str,
        role: int,
    ) -> Optional[Dict[str, Any]]:
        """
        Registers an agent on the SwarmAgentRegistry contract.

        Args:
            agent_id: Off-chain agent identifier (e.g., "ext-energy-bot-001")
            public_key: Agent's Ed25519 public key (hex string)
            role: Agent role enum (0=DATA_CONSUMER, 1=DATA_PROVIDER,
                  2=VERIFIER, 3=BROKER, 4=OBSERVER)

        Returns:
            Transaction receipt dict, or None if failed/not connected.

        Note:
            Uses keccak256(agent_id) as the on-chain key.
            Idempotent — re-registering updates the existing record.
        """
        if not self._agent_registry_connected:
            logger.warning(
                "BLOCKCHAIN: AgentRegistry not connected — "
                "agent not registered on-chain."
            )
            return None

        try:
            agent_id_hash = self._to_bytes32(agent_id)
            public_key_hash = self._to_bytes32(public_key)

            tx = self._agent_contract.functions.registerAgent(
                agent_id_hash,
                public_key_hash,
                role,
            )

            receipt = self._send_transaction(tx)
            if receipt:
                self._stats["agents_registered"] += 1
                logger.info(
                    f"AGENT REGISTERED ON-CHAIN: {agent_id} "
                    f"-> tx={receipt['transactionHash'][:18]}..."
                )
            return receipt

        except Exception as exc:
            self._stats["failed_transactions"] += 1
            logger.error(f"AGENT REGISTRATION FAILED: {exc}")
            return None

    def update_agent_reputation(
        self,
        agent_id: str,
        new_score: int,
    ) -> Optional[Dict[str, Any]]:
        """
        Updates an agent's reputation score on-chain.

        Args:
            agent_id: Off-chain agent identifier
            new_score: New reputation score (0–100)

        Returns:
            Transaction receipt dict, or None if failed/not connected.

        Note:
            Only The Last Bastion operators can update reputation.
            Score reflects cumulative task performance from off-chain verdicts.
        """
        if not self._agent_registry_connected:
            logger.warning(
                "BLOCKCHAIN: AgentRegistry not connected — "
                "reputation not updated on-chain."
            )
            return None

        try:
            agent_id_hash = self._to_bytes32(agent_id)

            tx = self._agent_contract.functions.updateReputation(
                agent_id_hash,
                new_score,
            )

            receipt = self._send_transaction(tx)
            if receipt:
                self._stats["reputation_updates"] += 1
                logger.info(
                    f"REPUTATION UPDATED ON-CHAIN: {agent_id} -> {new_score}/100 "
                    f"tx={receipt['transactionHash'][:18]}..."
                )
            return receipt

        except Exception as exc:
            self._stats["failed_transactions"] += 1
            logger.error(f"REPUTATION UPDATE FAILED: {exc}")
            return None

    def register_service_on_chain(
        self,
        service_id: str,
        provider_id: str,
        price_credits: float,
        tags: Optional[List[str]] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        Registers a service listing on the SwarmAgentRegistry contract.

        Args:
            service_id: Service identifier (e.g., "svc-data-extraction")
            provider_id: Agent ID of the service provider
            price_credits: Base price in credits (e.g., 5.0)
            tags: List of tag strings (e.g., ["energy", "nz", "web"])

        Returns:
            Transaction receipt dict, or None if failed/not connected.
        """
        if not self._agent_registry_connected:
            logger.warning(
                "BLOCKCHAIN: AgentRegistry not connected — "
                "service not registered on-chain."
            )
            return None

        try:
            service_id_hash = self._to_bytes32(service_id)
            provider_id_hash = self._to_bytes32(provider_id)
            price_fixed = int(price_credits * 1_000_000)  # × 1e6 fixed-point
            tag_hashes = [
                self._to_bytes32(tag) for tag in (tags or [])
            ]

            tx = self._agent_contract.functions.registerService(
                service_id_hash,
                provider_id_hash,
                price_fixed,
                tag_hashes,
            )

            receipt = self._send_transaction(tx)
            if receipt:
                logger.info(
                    f"SERVICE REGISTERED ON-CHAIN: {service_id} "
                    f"by {provider_id} @ {price_credits} credits "
                    f"-> tx={receipt['transactionHash'][:18]}..."
                )
            return receipt

        except Exception as exc:
            self._stats["failed_transactions"] += 1
            logger.error(f"SERVICE REGISTRATION FAILED: {exc}")
            return None

    def record_task_receipt(
        self,
        task_id: str,
        consumer_id: str,
        provider_id: str,
        service_id: str,
        credits_charged: float,
        outcome: int,
        proof_hash: str = "",
    ) -> Optional[Dict[str, Any]]:
        """
        Records a completed task receipt on-chain.

        Args:
            task_id: Off-chain task identifier
            consumer_id: Agent who requested the task
            provider_id: Agent who performed the task
            service_id: Which service was used
            credits_charged: Credits consumed (e.g., 5.3)
            outcome: Task result (0=COMPLETED, 1=FAILED, 2=DISPUTED)
            proof_hash: Optional link to SwarmProofRegistry proof hash

        Returns:
            Transaction receipt dict, or None if failed/not connected.
        """
        if not self._agent_registry_connected:
            logger.warning(
                "BLOCKCHAIN: AgentRegistry not connected — "
                "task receipt not recorded on-chain."
            )
            return None

        try:
            task_id_hash = self._to_bytes32(task_id)
            consumer_id_hash = self._to_bytes32(consumer_id)
            provider_id_hash = self._to_bytes32(provider_id)
            service_id_hash = self._to_bytes32(service_id)
            credits_fixed = int(credits_charged * 1_000_000)

            # Proof hash: link to SwarmProofRegistry, or zero bytes if none
            if proof_hash:
                hex_str = (
                    proof_hash[2:]
                    if proof_hash.startswith("0x")
                    else proof_hash
                )
                proof_bytes = bytes.fromhex(hex_str.ljust(64, "0")[:64])
            else:
                proof_bytes = b"\x00" * 32

            tx = self._agent_contract.functions.recordTaskReceipt(
                task_id_hash,
                consumer_id_hash,
                provider_id_hash,
                service_id_hash,
                credits_fixed,
                outcome,
                proof_bytes,
            )

            receipt = self._send_transaction(tx)
            if receipt:
                self._stats["task_receipts_recorded"] += 1
                outcome_names = {0: "COMPLETED", 1: "FAILED", 2: "DISPUTED"}
                logger.info(
                    f"TASK RECEIPT ON-CHAIN: {task_id} "
                    f"({outcome_names.get(outcome, 'UNKNOWN')}) "
                    f"{credits_charged} credits "
                    f"-> tx={receipt['transactionHash'][:18]}..."
                )
            return receipt

        except Exception as exc:
            self._stats["failed_transactions"] += 1
            logger.error(f"TASK RECEIPT FAILED: {exc}")
            return None

    def lookup_agent(
        self, agent_id: str
    ) -> Optional[Dict[str, Any]]:
        """
        Looks up an agent's on-chain record.

        READ-ONLY — no gas cost. Anyone can call this.

        Args:
            agent_id: Off-chain agent identifier

        Returns:
            Agent record dict with exists, role, status, reputation,
            tasks_completed, registered_at — or None if not connected.
        """
        if not self._agent_registry_connected:
            return None

        try:
            agent_id_hash = self._to_bytes32(agent_id)

            exists, role, status, reputation, tasks_completed, registered_at = (
                self._agent_contract.functions.getAgent(
                    agent_id_hash
                ).call()
            )

            if not exists:
                return {
                    "exists": False,
                    "agent_id": agent_id,
                    "source": "blockchain",
                }

            role_names = {
                0: "DATA_CONSUMER",
                1: "DATA_PROVIDER",
                2: "VERIFIER",
                3: "BROKER",
                4: "OBSERVER",
            }

            status_names = {
                0: "ACTIVE",
                1: "SUSPENDED",
                2: "REVOKED",
            }

            return {
                "exists": True,
                "agent_id": agent_id,
                "role": role_names.get(role, "UNKNOWN"),
                "status": status_names.get(status, "UNKNOWN"),
                "reputation_score": reputation,
                "tasks_completed": tasks_completed,
                "registered_at": registered_at,
                "source": "blockchain",
            }

        except Exception as exc:
            logger.error(f"AGENT LOOKUP FAILED: {exc}")
            return None

    def get_agent_registry_stats(self) -> Optional[Dict[str, Any]]:
        """
        Gets on-chain statistics from the SwarmAgentRegistry.

        READ-ONLY — no gas cost.
        """
        if not self._agent_registry_connected:
            return None

        try:
            agents_, services_, receipts_, credits_ = (
                self._agent_contract.functions.getStats().call()
            )

            return {
                "total_agents": agents_,
                "total_services": services_,
                "total_receipts": receipts_,
                "total_credits_transacted": credits_ / 1_000_000,
                "source": "blockchain",
            }

        except Exception as exc:
            logger.error(f"AGENT REGISTRY STATS FAILED: {exc}")
            return None

    @staticmethod
    def _agent_registry_inline_abi() -> List[Dict]:
        """
        Inline ABI for SwarmAgentRegistry.

        Matches the deployed Solidity contract exactly.
        Used as fallback when the compiled ABI file is not present.
        """
        return [
            {
                "inputs": [],
                "stateMutability": "nonpayable",
                "type": "constructor",
            },
            # registerAgent(bytes32, bytes32, uint8)
            {
                "inputs": [
                    {"name": "agentIdHash", "type": "bytes32"},
                    {"name": "publicKeyHash", "type": "bytes32"},
                    {"name": "role", "type": "uint8"},
                ],
                "name": "registerAgent",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            },
            # updateReputation(bytes32, uint256)
            {
                "inputs": [
                    {"name": "agentIdHash", "type": "bytes32"},
                    {"name": "newScore", "type": "uint256"},
                ],
                "name": "updateReputation",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            },
            # setAgentStatus(bytes32, uint8)
            {
                "inputs": [
                    {"name": "agentIdHash", "type": "bytes32"},
                    {"name": "newStatus", "type": "uint8"},
                ],
                "name": "setAgentStatus",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            },
            # registerService(bytes32, bytes32, uint256, bytes32[])
            {
                "inputs": [
                    {"name": "serviceIdHash", "type": "bytes32"},
                    {"name": "providerIdHash", "type": "bytes32"},
                    {"name": "priceCredits", "type": "uint256"},
                    {"name": "tags", "type": "bytes32[]"},
                ],
                "name": "registerService",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            },
            # deactivateService(bytes32)
            {
                "inputs": [
                    {"name": "serviceIdHash", "type": "bytes32"},
                ],
                "name": "deactivateService",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            },
            # recordTaskReceipt(bytes32, bytes32, bytes32, bytes32, uint256, uint8, bytes32)
            {
                "inputs": [
                    {"name": "taskIdHash", "type": "bytes32"},
                    {"name": "consumerIdHash", "type": "bytes32"},
                    {"name": "providerIdHash", "type": "bytes32"},
                    {"name": "serviceIdHash", "type": "bytes32"},
                    {"name": "creditsCharged", "type": "uint256"},
                    {"name": "outcome", "type": "uint8"},
                    {"name": "proofHash", "type": "bytes32"},
                ],
                "name": "recordTaskReceipt",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            },
            # getAgent(bytes32) -> (bool, uint8, uint8, uint256, uint256, uint256)
            {
                "inputs": [
                    {"name": "agentIdHash", "type": "bytes32"},
                ],
                "name": "getAgent",
                "outputs": [
                    {"name": "exists", "type": "bool"},
                    {"name": "role", "type": "uint8"},
                    {"name": "status", "type": "uint8"},
                    {"name": "reputationScore", "type": "uint256"},
                    {"name": "tasksCompleted", "type": "uint256"},
                    {"name": "registeredAt", "type": "uint256"},
                ],
                "stateMutability": "view",
                "type": "function",
            },
            # getService(bytes32) -> (bool, bytes32, uint256, bool, uint256)
            {
                "inputs": [
                    {"name": "serviceIdHash", "type": "bytes32"},
                ],
                "name": "getService",
                "outputs": [
                    {"name": "exists", "type": "bool"},
                    {"name": "providerIdHash", "type": "bytes32"},
                    {"name": "priceCredits", "type": "uint256"},
                    {"name": "isActive", "type": "bool"},
                    {"name": "registeredAt", "type": "uint256"},
                ],
                "stateMutability": "view",
                "type": "function",
            },
            # getTaskReceipt(bytes32) -> (bool, bytes32, bytes32, uint256, uint8, bytes32, uint256)
            {
                "inputs": [
                    {"name": "taskIdHash", "type": "bytes32"},
                ],
                "name": "getTaskReceipt",
                "outputs": [
                    {"name": "exists", "type": "bool"},
                    {"name": "consumerIdHash", "type": "bytes32"},
                    {"name": "providerIdHash", "type": "bytes32"},
                    {"name": "creditsCharged", "type": "uint256"},
                    {"name": "outcome", "type": "uint8"},
                    {"name": "proofHash", "type": "bytes32"},
                    {"name": "completedAt", "type": "uint256"},
                ],
                "stateMutability": "view",
                "type": "function",
            },
            # getStats() -> (uint256, uint256, uint256, uint256)
            {
                "inputs": [],
                "name": "getStats",
                "outputs": [
                    {"name": "agents_", "type": "uint256"},
                    {"name": "services_", "type": "uint256"},
                    {"name": "receipts_", "type": "uint256"},
                    {"name": "creditsTransacted_", "type": "uint256"},
                ],
                "stateMutability": "view",
                "type": "function",
            },
        ]

